name: Feature request
description: Suggest an idea for this project
labels:
  - feature
body:
  - type: dropdown
    id: product
    attributes:
      label: For?
      multiple: true
      options:
        - Garry's Mod
    validations:
      required: true
  - type: textarea
    id: what-to-add
    attributes:
      label: What do you want us to add?
      description: Describe in detail what you're wanting us to add to the server.
      placeholder: I'm wanting ...
    validations:
      required: true
  - type: textarea
    id: how-work
    attributes:
      label: How would you like it to work?
      description: Describe in detail how the feature should work
      placeholder: I want it to work by...
    validations:
      required: true
  - type: textarea
    id: extra-context
    attributes:
      label: Additional context
      description: Any extra details on the feature you're requesting
